blank_issues_enabled: false
contact_links:
  - name: Questions about Solitude
    url: https://github.com/wleelw/hexo-theme-solitude/discussions
    about: 一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.

  - name: Solitude Q&A
    url: https://docs.wzsco.top/guide/FAQ
    about: Solitude Q&A
    
  - name: QQ 群
    url: https://qm.qq.com/q/WA2DGLfKW6
    about: '群号 773016811'
